# This is a basic workflow to help you get started with Actions

name: Repair AV files v3
# description: an hourly script to fix duration bugs with generated MP4 and MP3 files

on:
  #schedule:
  #  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  repair-av:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # NODE
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install node packages
        run: yarn install

      - name: get data
        run: yarn repair-av
        env:
          APP_AWS_BUCKET: ${{secrets.APP_AWS_BUCKET}}
          APP_AWS_REGION: ${{secrets.APP_AWS_REGION}}
          APP_AWS_ACCOUNT_ID: ${{secrets.APP_AWS_ACCOUNT_ID}}
          APP_AWS_ACCESS_KEY_ID: ${{secrets.APP_AWS_ACCESS_KEY_ID}}
          APP_AWS_SECRET_ACCESS_KEY: ${{secrets.APP_AWS_SECRET_ACCESS_KEY}}
          REPAIR_AV_FILE_LIMIT: 5

      - name: timestamp update
        run: yarn timestamp-update
        env:
          TIMESTAMP_PATH: ./scripts/repair-av-last-run.txt

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Atlas Bot"
          git add -A
          git commit -m "Repair AV [skip ci]" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
