# This is a basic workflow to help you get started with Actions

name: Repair AV files
description: an hourly script to fix duration bugs with generated MP4 and MP3 files

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  interpolate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 14.x

    steps:
      - uses: actions/checkout@master
      
      # NODE
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install node packages
        run: npm install

      - name: get data
        run: yarn repair-av
        env:
          APP_AWS_BUCKET: ${{secrets.APP_AWS_BUCKET}}
          APP_AWS_REGION: ${{secrets.APP_AWS_REGION}}
          APP_AWS_ACCOUNT_ID: ${{secrets.APP_AWS_ACCOUNT_ID}}
          APP_AWS_ACCESS_KEY_ID: ${{secrets.APP_AWS_ACCESS_KEY_ID}}
          APP_AWS_SECRET_ACCESS_KEY: ${{secrets.APP_AWS_SECRET_ACCESS_KEY}}

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Atlas Bot"
          git add -A
          git commit -m "Repair AV [skip ci]" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main