# This is a basic workflow to help you get started with Actions

name: Update Public CDN 0.0.2
# description: manage the public CDN

on:
  schedule:
    - cron: '45 0 * * *'
  workflow_dispatch:

jobs:
  update-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install node packages
        run: npm install
      - name: Update CDN
        run: yarn update-cdn
        env:
          APP_AWS_BUCKET: ${{secrets.APP_AWS_BUCKET}}
          APP_AWS_REGION: ${{secrets.APP_AWS_REGION}}
          APP_AWS_ACCOUNT_ID: ${{secrets.APP_AWS_ACCOUNT_ID}}
          APP_AWS_ACCESS_KEY_ID: ${{secrets.APP_AWS_ACCESS_KEY_ID}}
          APP_AWS_SECRET_ACCESS_KEY: ${{secrets.APP_AWS_SECRET_ACCESS_KEY}}
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Atlas Bot"
          git add -A
          git commit -m "Repair AV [skip ci]" -a
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main